domain: exanova-y.github.io
url: https://exanova-y.github.io
baseurl: ""

title: indiraschka@comonad ~ %
email: yoyoyuan1729@gmail.com
author: Yoyo Yuan

lang: en

plugins:
  - jekyll-seo-tag

color: "#a635fe"
# disqus:
#   shortname: example-com
#
rrss:
  email: "yoyoyuan1729@gmail.com"
  telegram: "https://t.me/indiraschka"
  x: "https://x.com/indiraschka"
